#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
      int a,b,c;

	 printf("enter the 1 no ");
	 scanf("%d",&a);

	 printf("enter the 2 no ");
	 scanf("%d",&b);

	 printf("enter the 3 no ");
	 scanf("%d",&c);

      printf("\nGREATEST NUMBER \n \n");
     {
      if
	 (a>=b)
     {
      if
	 (a>=b)
	 printf("%d",a);

      else
	 printf("%d",b);

      }
      else

      {
      if
	(c>b)
	printf("%d",c);

      else
	  printf("%d",b);
       }

      }
getch();
}