/* program for cheacking ascii value of character input by user */

#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
	      char o;

	      printf("ENTER THE CHARACTER FOR ASCII VALUE\n");
	      printf("---------------------------------------\n");

	      scanf("%c",&o);

	     printf("\nOUT PUT\n");
	     printf("---------------------------------------\n");

	     printf("%d",o);

getch();
}